io = File.open('units.c', 'w')
io.puts "// Copyright (c) Microsoft Corporation. All rights reserved."
io.puts "// Licensed under the MIT License. See the LICENSE.txt file in the project root"
io.puts "// for the license information."
io.puts ''
io.puts "// This file was generated by #{__FILE__}. Do not edit."
io.puts ''

tests = ARGV.to_a
units = []
tests.each do |test|
  unit = File.basename(test, '.c')
  units << unit
  io.puts "static void\n#{unit}(void)\n{\n"
  File.read(test).scan(/^#{unit}([^(]+)/).each do |suffix|
    subunit = "#{unit}#{suffix[0]}"
    io.puts "    current_unit = \"#{subunit}\";"
    io.puts "    void #{subunit}(void);"
    io.puts "    #{subunit}();"
  end
  io.puts '}'
  io.puts ''
end

io.puts "void\nrun_all_units(void)\n{\n"
units.each do |unit|
  io.puts "    #{unit}();"
end
io.puts '}'

io.close
