io = File.open('units.c', 'w')
io.puts "// This file was generated by #{__FILE__}. Do not edit."

tests = ARGV.to_a
units = []
tests.each do |test|
  io.puts "#include \"#{test}\""
  unit = File.basename(test, '.c')
  units << unit
  io.puts "static void #{unit}(void)\n{\n"
  File.read(test).scan(/^#{unit}([^(]+)/).each do |suffix|
    subunit = "#{unit}#{suffix[0]}"
    io.puts "    current_unit = \"#{subunit}\";"
    io.puts "    #{subunit}();"
  end
  io.puts '}'
end

io.puts "static void run_all_units(void)\n{\n"
units.each do |unit|
  io.puts "    #{unit}();"
end
io.puts '}'

io.close
