// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See the LICENSE.txt file in the project root
// for the license information.

// This file was generated by generate_units.rb. Do not edit.

static void
test_default_values(void)
{
    current_unit = "test_default_values1";
    void test_default_values1(void);
    test_default_values1();
    current_unit = "test_default_values2";
    void test_default_values2(void);
    test_default_values2();
    current_unit = "test_default_values3";
    void test_default_values3(void);
    test_default_values3();
}

static void
test_children(void)
{
    current_unit = "test_children1";
    void test_children1(void);
    test_children1();
    current_unit = "test_children2";
    void test_children2(void);
    test_children2();
    current_unit = "test_children3";
    void test_children3(void);
    test_children3();
    current_unit = "test_children4";
    void test_children4(void);
    test_children4();
    current_unit = "test_children5";
    void test_children5(void);
    test_children5();
    current_unit = "test_children6";
    void test_children6(void);
    test_children6();
}

static void
test_managed_ptr(void)
{
    current_unit = "test_managed_ptr1";
    void test_managed_ptr1(void);
    test_managed_ptr1();
}

static void
test_basis(void)
{
    current_unit = "test_basis1";
    void test_basis1(void);
    test_basis1();
    current_unit = "test_basis2";
    void test_basis2(void);
    test_basis2();
    current_unit = "test_basis3";
    void test_basis3(void);
    test_basis3();
}

static void
test_grow(void)
{
    current_unit = "test_grow1";
    void test_grow1(void);
    test_grow1();
    current_unit = "test_grow2";
    void test_grow2(void);
    test_grow2();
    current_unit = "test_grow3";
    void test_grow3(void);
    test_grow3();
    current_unit = "test_grow4";
    void test_grow4(void);
    test_grow4();
    current_unit = "test_grow5";
    void test_grow5(void);
    test_grow5();
    current_unit = "test_grow6";
    void test_grow6(void);
    test_grow6();
    current_unit = "test_grow7";
    void test_grow7(void);
    test_grow7();
    current_unit = "test_grow8";
    void test_grow8(void);
    test_grow8();
}

static void
test_shrink(void)
{
    current_unit = "test_shrink1";
    void test_shrink1(void);
    test_shrink1();
    current_unit = "test_shrink2";
    void test_shrink2(void);
    test_shrink2();
    current_unit = "test_shrink3";
    void test_shrink3(void);
    test_shrink3();
    current_unit = "test_shrink4";
    void test_shrink4(void);
    test_shrink4();
    current_unit = "test_shrink5";
    void test_shrink5(void);
    test_shrink5();
    current_unit = "test_shrink6";
    void test_shrink6(void);
    test_shrink6();
    current_unit = "test_shrink7";
    void test_shrink7(void);
    test_shrink7();
}

static void
test_direction(void)
{
    current_unit = "test_direction1";
    void test_direction1(void);
    test_direction1();
    current_unit = "test_direction2";
    void test_direction2(void);
    test_direction2();
    current_unit = "test_direction3";
    void test_direction3(void);
    test_direction3();
    current_unit = "test_direction4";
    void test_direction4(void);
    test_direction4();
}

static void
test_order(void)
{
    current_unit = "test_order1";
    void test_order1(void);
    test_order1();
    current_unit = "test_order2";
    void test_order2(void);
    test_order2();
    current_unit = "test_order3";
    void test_order3(void);
    test_order3();
    current_unit = "test_order4";
    void test_order4(void);
    test_order4();
}

static void
test_align_self(void)
{
    current_unit = "test_align_self1";
    void test_align_self1(void);
    test_align_self1();
    current_unit = "test_align_self2";
    void test_align_self2(void);
    test_align_self2();
    current_unit = "test_align_self3";
    void test_align_self3(void);
    test_align_self3();
    current_unit = "test_align_self4";
    void test_align_self4(void);
    test_align_self4();
    current_unit = "test_align_self5";
    void test_align_self5(void);
    test_align_self5();
    current_unit = "test_align_self6";
    void test_align_self6(void);
    test_align_self6();
}

static void
test_align_items(void)
{
    current_unit = "test_align_items1";
    void test_align_items1(void);
    test_align_items1();
    current_unit = "test_align_items2";
    void test_align_items2(void);
    test_align_items2();
    current_unit = "test_align_items3";
    void test_align_items3(void);
    test_align_items3();
    current_unit = "test_align_items4";
    void test_align_items4(void);
    test_align_items4();
    current_unit = "test_align_items5";
    void test_align_items5(void);
    test_align_items5();
}

static void
test_wrap(void)
{
    current_unit = "test_wrap1";
    void test_wrap1(void);
    test_wrap1();
    current_unit = "test_wrap2";
    void test_wrap2(void);
    test_wrap2();
    current_unit = "test_wrap3";
    void test_wrap3(void);
    test_wrap3();
    current_unit = "test_wrap4";
    void test_wrap4(void);
    test_wrap4();
    current_unit = "test_wrap5";
    void test_wrap5(void);
    test_wrap5();
    current_unit = "test_wrap6";
    void test_wrap6(void);
    test_wrap6();
    current_unit = "test_wrap7";
    void test_wrap7(void);
    test_wrap7();
    current_unit = "test_wrap8";
    void test_wrap8(void);
    test_wrap8();
    current_unit = "test_wrap9";
    void test_wrap9(void);
    test_wrap9();
    current_unit = "test_wrap10";
    void test_wrap10(void);
    test_wrap10();
    current_unit = "test_wrap11";
    void test_wrap11(void);
    test_wrap11();
    current_unit = "test_wrap12";
    void test_wrap12(void);
    test_wrap12();
    current_unit = "test_wrap13";
    void test_wrap13(void);
    test_wrap13();
    current_unit = "test_wrap14";
    void test_wrap14(void);
    test_wrap14();
    current_unit = "test_wrap15";
    void test_wrap15(void);
    test_wrap15();
    current_unit = "test_wrap16";
    void test_wrap16(void);
    test_wrap16();
    current_unit = "test_wrap17";
    void test_wrap17(void);
    test_wrap17();
    current_unit = "test_wrap18";
    void test_wrap18(void);
    test_wrap18();
    current_unit = "test_wrap19";
    void test_wrap19(void);
    test_wrap19();
    current_unit = "test_wrap20";
    void test_wrap20(void);
    test_wrap20();
    current_unit = "test_wrap21";
    void test_wrap21(void);
    test_wrap21();
    current_unit = "test_wrap22";
    void test_wrap22(void);
    test_wrap22();
    current_unit = "test_wrap23";
    void test_wrap23(void);
    test_wrap23();
    current_unit = "test_wrap24";
    void test_wrap24(void);
    test_wrap24();
    current_unit = "test_wrap25";
    void test_wrap25(void);
    test_wrap25();
    current_unit = "test_wrap26";
    void test_wrap26(void);
    test_wrap26();
}

static void
test_justify_content(void)
{
    current_unit = "test_justify_content1";
    void test_justify_content1(void);
    test_justify_content1();
    current_unit = "test_justify_content2";
    void test_justify_content2(void);
    test_justify_content2();
    current_unit = "test_justify_content3";
    void test_justify_content3(void);
    test_justify_content3();
    current_unit = "test_justify_content4";
    void test_justify_content4(void);
    test_justify_content4();
    current_unit = "test_justify_content5";
    void test_justify_content5(void);
    test_justify_content5();
    current_unit = "test_justify_content6";
    void test_justify_content6(void);
    test_justify_content6();
    current_unit = "test_justify_content7";
    void test_justify_content7(void);
    test_justify_content7();
    current_unit = "test_justify_content8";
    void test_justify_content8(void);
    test_justify_content8();
    current_unit = "test_justify_content9";
    void test_justify_content9(void);
    test_justify_content9();
    current_unit = "test_justify_content10";
    void test_justify_content10(void);
    test_justify_content10();
    current_unit = "test_justify_content11";
    void test_justify_content11(void);
    test_justify_content11();
    current_unit = "test_justify_content12";
    void test_justify_content12(void);
    test_justify_content12();
    current_unit = "test_justify_content13";
    void test_justify_content13(void);
    test_justify_content13();
    current_unit = "test_justify_content14";
    void test_justify_content14(void);
    test_justify_content14();
    current_unit = "test_justify_content15";
    void test_justify_content15(void);
    test_justify_content15();
    current_unit = "test_justify_content16";
    void test_justify_content16(void);
    test_justify_content16();
    current_unit = "test_justify_content17";
    void test_justify_content17(void);
    test_justify_content17();
    current_unit = "test_justify_content18";
    void test_justify_content18(void);
    test_justify_content18();
}

static void
test_align_content(void)
{
    current_unit = "test_align_content1";
    void test_align_content1(void);
    test_align_content1();
    current_unit = "test_align_content2";
    void test_align_content2(void);
    test_align_content2();
    current_unit = "test_align_content3";
    void test_align_content3(void);
    test_align_content3();
    current_unit = "test_align_content4";
    void test_align_content4(void);
    test_align_content4();
    current_unit = "test_align_content5";
    void test_align_content5(void);
    test_align_content5();
    current_unit = "test_align_content6";
    void test_align_content6(void);
    test_align_content6();
}

static void
test_position(void)
{
    current_unit = "test_position1";
    void test_position1(void);
    test_position1();
    current_unit = "test_position2";
    void test_position2(void);
    test_position2();
    current_unit = "test_position3";
    void test_position3(void);
    test_position3();
    current_unit = "test_position4";
    void test_position4(void);
    test_position4();
    current_unit = "test_position5";
    void test_position5(void);
    test_position5();
    current_unit = "test_position6";
    void test_position6(void);
    test_position6();
    current_unit = "test_position7";
    void test_position7(void);
    test_position7();
    current_unit = "test_position8";
    void test_position8(void);
    test_position8();
}

static void
test_margin(void)
{
    current_unit = "test_margin1";
    void test_margin1(void);
    test_margin1();
    current_unit = "test_margin2";
    void test_margin2(void);
    test_margin2();
    current_unit = "test_margin3";
    void test_margin3(void);
    test_margin3();
    current_unit = "test_margin4";
    void test_margin4(void);
    test_margin4();
    current_unit = "test_margin5";
    void test_margin5(void);
    test_margin5();
    current_unit = "test_margin6";
    void test_margin6(void);
    test_margin6();
    current_unit = "test_margin7";
    void test_margin7(void);
    test_margin7();
    current_unit = "test_margin8";
    void test_margin8(void);
    test_margin8();
    current_unit = "test_margin9";
    void test_margin9(void);
    test_margin9();
    current_unit = "test_margin10";
    void test_margin10(void);
    test_margin10();
}

static void
test_padding(void)
{
    current_unit = "test_padding1";
    void test_padding1(void);
    test_padding1();
    current_unit = "test_padding2";
    void test_padding2(void);
    test_padding2();
    current_unit = "test_padding3";
    void test_padding3(void);
    test_padding3();
    current_unit = "test_padding4";
    void test_padding4(void);
    test_padding4();
    current_unit = "test_padding5";
    void test_padding5(void);
    test_padding5();
}

static void
test_self_sizing(void)
{
    current_unit = "test_self_sizing_dummy0";
    void test_self_sizing_dummy0(void);
    test_self_sizing_dummy0();
    current_unit = "test_self_sizing_dummy1";
    void test_self_sizing_dummy1(void);
    test_self_sizing_dummy1();
    current_unit = "test_self_sizing_dummy2";
    void test_self_sizing_dummy2(void);
    test_self_sizing_dummy2();
    current_unit = "test_self_sizing_dummy3";
    void test_self_sizing_dummy3(void);
    test_self_sizing_dummy3();
    current_unit = "test_self_sizing_dummy4";
    void test_self_sizing_dummy4(void);
    test_self_sizing_dummy4();
    current_unit = "test_self_sizing_dummy5";
    void test_self_sizing_dummy5(void);
    test_self_sizing_dummy5();
    current_unit = "test_self_sizing_dummy6";
    void test_self_sizing_dummy6(void);
    test_self_sizing_dummy6();
    current_unit = "test_self_sizing_nan";
    void test_self_sizing_nan(void);
    test_self_sizing_nan();
    current_unit = "test_self_sizing1";
    void test_self_sizing1(void);
    test_self_sizing1();
    current_unit = "test_self_sizing2";
    void test_self_sizing2(void);
    test_self_sizing2();
    current_unit = "test_self_sizing3";
    void test_self_sizing3(void);
    test_self_sizing3();
    current_unit = "test_self_sizing4";
    void test_self_sizing4(void);
    test_self_sizing4();
    current_unit = "test_self_sizing5";
    void test_self_sizing5(void);
    test_self_sizing5();
    current_unit = "test_self_sizing6";
    void test_self_sizing6(void);
    test_self_sizing6();
    current_unit = "test_self_sizing7";
    void test_self_sizing7(void);
    test_self_sizing7();
}

void
run_all_units(void)
{
    test_default_values();
    test_children();
    test_managed_ptr();
    test_basis();
    test_grow();
    test_shrink();
    test_direction();
    test_order();
    test_align_self();
    test_align_items();
    test_wrap();
    test_justify_content();
    test_align_content();
    test_position();
    test_margin();
    test_padding();
    test_self_sizing();
}
